### ISSUE TITLE
Pushing updated version

### ISSUE THREAD

**Issue by Stono** [danwrong/restler#216]
Please see my comment on closed issue https://github.com/danwrong/restler/issues/186 - we could do with a version bump with the updated package.json to address the vuln in 'qs' pushing to npmjs.org

**Comment by jamlen** [comment]
:+1:

**Comment by FredGolem** [comment]
+1

**Comment by markhigham** [comment]
+1

**Comment by cookie-bytes** [comment]
+1

**Comment by easternbloc** [comment]
Done. Thanks guise.
