### ISSUE TITLE
DO NOT USE THIS LIBRARY, IT IS BROKEN TO HELL

### ISSUE THREAD

**Issue by jpike88** [danwrong/restler#239]
Please use node-rest-client instead, don't make the same mistake I did.

**Comment by BryanDollery** [comment]
Odd. I recently used it with no problems for a big data migration project. I can see that it has probably been abandoned, but it seems to me to be working ok-ish.

**Comment by sandorfr** [comment]
@jpike88 would be nice to document whats broken a bit more.
