### ISSUE TITLE
Send a file from memory?

### ISSUE THREAD

**Issue by EddieOne** [danwrong/restler#258]
`'sound[file]': rest.file('doug-e-fresh_the-show.mp3', null, 321567, null, 'audio/mpeg')`

It is possible to send a buffer maybe?

`sound[file]: Buffer(string_img, 'base64')`

**Comment by amitguptagwl** [comment]
This project seems inactive from last 2 years. But you can have a look on https://www.npmjs.com/package/restler-base

**Comment by EddieOne** [comment]
Let's close
